import { defineField, defineType } from 'sanity';

export default defineType({
  name: 'unit',
  title: 'Unit',
  type: 'document',
  groups: [
    { name: 'basics', title: 'Basics', default: true },
    { name: 'photos', title: 'Photos' },
    { name: 'features', title: 'Features' },
    { name: 'pricing', title: 'Pricing' },
    { name: 'links', title: 'Links' },
  ],
  fields: [
    defineField({
      name: 'unitNumber',
      title: 'Unit number',
      type: 'string',
      group: 'basics',
      description: 'The true identifier (1–8). Shows on door + lease.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'name',
      title: 'Name',
      type: 'string',
      group: 'basics',
      description: 'Animal name — Bobcat, Chipmunk, Fox, etc.',
    }),
    defineField({
      name: 'order',
      title: 'Sort order',
      type: 'number',
      group: 'basics',
      initialValue: 1,
      description: 'Lower numbers show first on /units. Default to the unit number.',
    }),
    defineField({
      name: 'type',
      title: 'Type',
      type: 'string',
      group: 'basics',
      options: {
        list: [
          { title: 'Studio', value: 'studio' },
          { title: '2 bedroom', value: '2br' },
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'basics',
      options: {
        list: [
          { title: 'Available now', value: 'available' },
          { title: 'Leased', value: 'leased' },
          { title: 'Coming soon', value: 'coming-soon' },
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'availableDate',
      title: 'Available date',
      type: 'date',
      group: 'basics',
      description: 'Only used when status is "Coming soon".',
      hidden: ({ parent }) => parent?.status !== 'coming-soon',
    }),
    defineField({
      name: 'squareFeet',
      title: 'Square feet',
      type: 'number',
      group: 'basics',
      validation: (Rule) => Rule.required().positive(),
    }),
    defineField({
      name: 'beds',
      title: 'Beds',
      type: 'number',
      group: 'basics',
      initialValue: 0,
      description: 'Use 0 for studios.',
    }),
    defineField({
      name: 'baths',
      title: 'Baths',
      type: 'number',
      group: 'basics',
      initialValue: 1,
    }),
    defineField({
      name: 'shortDescription',
      title: 'Short description',
      type: 'text',
      rows: 3,
      group: 'basics',
      description: 'One or two sentences for the unit card and detail page intro.',
    }),
    defineField({
      name: 'features',
      title: 'In-unit features',
      type: 'array',
      group: 'features',
      of: [{ type: 'unitFeature' }],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'photos',
      title: 'Photos',
      type: 'array',
      group: 'photos',
      of: [{ type: 'unitPhoto' }],
      description: 'Drag to reorder. The first photo is the card hero.',
      validation: (Rule) => Rule.min(1).error('Each unit needs at least one photo.'),
    }),
    defineField({
      name: 'pricing',
      title: 'Pricing',
      type: 'pricing',
      group: 'pricing',
    }),
    defineField({
      name: 'applyUrl',
      title: 'Avail application URL',
      type: 'url',
      group: 'links',
      description: 'The unit-specific Avail listing link.',
    }),
    defineField({
      name: 'shortTermAvailable',
      title: 'Also bookable on Airbnb (short stays)',
      type: 'boolean',
      group: 'links',
      initialValue: false,
    }),
  ],
  orderings: [
    {
      title: 'Unit number',
      name: 'unitNumberAsc',
      by: [{ field: 'order', direction: 'asc' }],
    },
    {
      title: 'Status',
      name: 'statusAsc',
      by: [{ field: 'status', direction: 'asc' }, { field: 'order', direction: 'asc' }],
    },
  ],
  preview: {
    select: {
      title: 'name',
      subtitle: 'unitNumber',
      status: 'status',
      media: 'photos.0',
    },
    prepare: ({ title, subtitle, status, media }) => ({
      title: title || `Unit ${subtitle}`,
      subtitle: `Unit ${subtitle} · ${status || 'unknown'}`,
      media,
    }),
  },
});
